apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: forge
  labels:
    k8s-sandbox.dev/role: edge
spec:
  type: LoadBalancer
  selector:
    k8s-sandbox.dev/role: edge
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
